export const setupTemplate: any = {
  //!CPU
  cpu: {
    type: "cpu",
    manufacturer: "",
    model: "cpu",

    total_cores: 0,
    number_of_performance_cores: 0,
    number_of_efficient_cores: 0,
    total_threads: 0,
    boost_clock: 0,
    cache: 0,
    integrated_graphics: "",
    socket: "",
    architecture: "",
    launch_date: "",
    stock_cooler: { type: String, trim: true },

    //!Required
    //     imageM: [""],
    //     imageS: [""],
    imageM: "",
    imageS: "",
    //     specifications: [],
    price: 0,
    power: 0,
    quantity: 0,
    error: false,
    warning: "",
    available: "",
  },
  //!MOBO
  mobo: {
    type: "mobo",
    manufacturer: "",
    model: "mobo",

    platform: "",
    socket: "",
    chipset: "",
    ram_type: "",
    max_memory: "",
    form_factor: "",
    memory_speed_max: "",
    lan_speed_max: "",

    //!Required
    //     imageM: [""],
    //     imageS: [""],
    imageM: "",
    imageS: "",
    //     specifications: [],
    price: 0,
    power: 0,
    quantity: 0,
    error: false,
    warning: "",
    available: "",
  },
  //!RAM
  ram: {
    type: "ram",
    manufacturer: "",
    model: "ram",

    memory_size: "",
    speed: "",
    ram_type: "",
    CAS_latency: "",
    timing: "",

    //!Required
    //     imageM: [""],
    //     imageS: [""],
    imageM: "",
    imageS: "",
    //     specifications: [],
    price: 0,
    power: 0,
    quantity: 0,
    error: false,
    warning: "",
    available: "",
  },

  //!GPU
  gpu: {
    type: "gpu",
    manufacturer: "",
    model: "gpu",

    memory: "",
    memory_type: "",
    gpu_boost_clock: "",
    length: "",
    benchmark: 0,
    launch_date: "",

    //!Required
    //     imageM: [""],
    //     imageS: [""],
    imageM: "",
    imageS: "",
    //     specifications: [],
    price: 0,
    power: 0,
    quantity: 0,
    error: false,
    warning: "",
    available: "",
  },
  //!POWER
  power: {
    type: "power",
    manufacturer: "",
    model: "power",

    efficiency_rating: "",
    wattage: "",
    form_factor: "",
    modular: "",

    //!Required
    //     imageM: [""],
    //     imageS: [""],
    imageM: "",
    imageS: "",
    //     specifications: [],
    price: 0,
    power: 0,
    quantity: 0,
    error: false,
    warning: "",
    available: "",
  },

  //!CASE
  case: {
    type: "case",
    manufacturer: "",
    model: "case",

    form_factor: "",
    PSU: "no",
    height: 0,
    length: 0,
    width: 0,
    //!Required
    //     imageM: [""],
    //     imageS: [""],
    imageM: "",
    imageS: "",
    //     specifications: [],
    price: 0,
    power: 0,
    quantity: 0,
    error: false,
    warning: "",
    available: "",
  },
  //!NVME
  nvme: {
    type: "nvme",
    manufacturer: "",
    model: "nvme",

    capacity: "",
    read: "",
    write: "",
    TBW: "",
    MTBF: "",
    //!Required
    //     imageM: [""],
    //     imageS: [""],
    imageM: "",
    imageS: "",
    //     specifications: [],
    price: 0,
    power: 0,
    quantity: 0,
    error: false,
    warning: "",
    available: "",
  },
  //!SSD
  ssd: {
    type: "ssd",
    manufacturer: "",
    model: "ssd",

    capacity: "",
    read: "",
    write: "",
    TBW: "",
    form_factor: "",
    //!Required
    //     imageM: [""],
    //     imageS: [""],
    imageM: "",
    imageS: "",
    //     specifications: [],
    price: 0,
    power: 0,
    quantity: 0,
    error: false,
    warning: "",
    available: "",
  },
  //!HDD
  hdd: {
    type: "hdd",
    manufacturer: "",
    model: "hdd",

    capacity: "",
    rpm: 0,
    cache: 0,
    interface: "",
    form_factor: "",
    //!Required
    //     imageM: [""],
    //     imageS: [""],
    imageM: "",
    imageS: "",
    //     specifications: [],
    price: 0,
    power: 0,
    quantity: 0,
    error: false,
    warning: "",
    available: "",
  },
  //!COOLER
  cooler: {
    type: "cooler",
    manufacturer: "",
    model: "cooler",

    compatibility: "",
    cooler_type: "",
    noise_level: "",
    //!Required
    //     imageM: [""],
    //     imageS: [""],
    imageM: "",
    imageS: "",
    //     specifications: [],
    price: 0,
    power: 0,
    quantity: 0,
    error: false,
    warning: "",
    available: "",
  },
  //!FAN
  fan: {
    type: "fan",
    manufacturer: "",
    model: "fan",

    efficiency_rating: "",
    wattage: "",
    form_factor: "",
    modular: "",

    //!Required
    //     imageM: [""],
    //     imageS: [""],
    imageM: "",
    imageS: "",
    //     specifications: [],
    price: 0,
    power: 0,
    quantity: 0,
    error: false,
    warning: "",
    available: "",
  },
};
