export enum ActionType {
  SET_LOGIN = "SET_LOGIN ",
  SET_SETUP = "SET_SETUP ",
  RESET_SETUP = "RESET_SETUP ",
  RESET_ALL_ITEMS = "RESET_ALL_ITEMS",
  SET_SOCKET = "SET_SOCKET",
  SET_RAM_TYPE = "SET_RAM_TYPE",
  SET_COMPARE = "SET_COMPARE",
  DELETE_COMPARE = "DELETE_COMPARE",
  OPEN_MENU = "OPEN_MENU",
}
